### ISSUE TITLE
Password strength checking massively slows the user registration screen

### ISSUE THREAD

**Issue by salikhov** [jacobzipper/donationTrackerCS2340#40]

**Comment by salikhov** [comment]
8d19a3275053f3b2ad210a2549a588fdba20e665 but still slow because the async operation takes some time to complete. Does not freeze up the UI though.

**Comment by jacobzipper** [comment]
Much thanks for this. I noticed it was realllllllyyyy bad on my phone as well.

**Comment by James-OConnor** [comment]
Possible change instead of checking password on every single character change to checking when the characters in the string don't change for a period of time.

**Comment by jballen73** [comment]
Fixed with commit 8166a0b2dc695ca7e0a25fd04ebb12be66bf89d8
